BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SubAgent" (
	"id"	INTEGER,
	"Name"	TEXT
);
INSERT INTO "SubAgent" VALUES (1,'Mohamed');
INSERT INTO "SubAgent" VALUES (2,'Anis');
INSERT INTO "SubAgent" VALUES (3,'Sadam');
INSERT INTO "SubAgent" VALUES (4,'Razan');
INSERT INTO "SubAgent" VALUES (5,'Ali MLS');
INSERT INTO "SubAgent" VALUES (6,'Amudu');
INSERT INTO "SubAgent" VALUES (7,'Lucky');
INSERT INTO "SubAgent" VALUES (9,'Wickramasinghe');
INSERT INTO "SubAgent" VALUES (10,'Yasas Sri Services (Pvt) Ltd');
INSERT INTO "SubAgent" VALUES (11,'Calling Visa 11');
INSERT INTO "SubAgent" VALUES (12,'Subair');
INSERT INTO "SubAgent" VALUES (8,'Direct');
INSERT INTO "SubAgent" VALUES (13,'Ilyas Mohamed Mujeef');
INSERT INTO "SubAgent" VALUES (14,'Unique Recruitment');
INSERT INTO "SubAgent" VALUES (15,'Calling Visa');
INSERT INTO "SubAgent" VALUES (16,'Krisnan');
INSERT INTO "SubAgent" VALUES (100,'DUE');
INSERT INTO "SubAgent" VALUES (17,'Muthumohamed');
INSERT INTO "SubAgent" VALUES (18,'Lal');
INSERT INTO "SubAgent" VALUES (19,'GUNAWARDANA');
INSERT INTO "SubAgent" VALUES (20,'Samatha Yassari');
INSERT INTO "SubAgent" VALUES (21,'Suda');
INSERT INTO "SubAgent" VALUES (22,'Sumair');
INSERT INTO "SubAgent" VALUES (23,'Aliear Polonnaruwa');
INSERT INTO "SubAgent" VALUES (24,'MRS. Asala');
INSERT INTO "SubAgent" VALUES (25,'Azmy Stylo');
INSERT INTO "SubAgent" VALUES (26,'Ahamed');
INSERT INTO "SubAgent" VALUES (27,'Yaz Mohamed');
INSERT INTO "SubAgent" VALUES (28,'Yaz Travel');
INSERT INTO "SubAgent" VALUES (29,'Address Case');
INSERT INTO "SubAgent" VALUES (30,'Expense');
INSERT INTO "SubAgent" VALUES (31,'Hanifa Yaz Mohamed');
INSERT INTO "SubAgent" VALUES (200,'AllFile');
INSERT INTO "SubAgent" VALUES (32,'Zarook Ahmed Sub');
INSERT INTO "SubAgent" VALUES (101,'Due Temp');
INSERT INTO "SubAgent" VALUES (33,'Hafnawi');
INSERT INTO "SubAgent" VALUES (34,'Athik Galle');
INSERT INTO "SubAgent" VALUES (35,'Anu');
INSERT INTO "SubAgent" VALUES (36,'Buary Stylo');
INSERT INTO "SubAgent" VALUES (37,'Lucky');
INSERT INTO "SubAgent" VALUES (102,'Almehani');
INSERT INTO "SubAgent" VALUES (104,'Q');
INSERT INTO "SubAgent" VALUES (105,'Home');
INSERT INTO "SubAgent" VALUES (38,'Nisha');
INSERT INTO "SubAgent" VALUES (39,'Hassan Weligama');
INSERT INTO "SubAgent" VALUES (40,'AS Travels');
INSERT INTO "SubAgent" VALUES (41,'Gunasiri');
INSERT INTO "SubAgent" VALUES (42,'Farook Odamavadi');
INSERT INTO "SubAgent" VALUES (43,'Kandy Lanka ');
INSERT INTO "SubAgent" VALUES (44,'Shukrie S M');
INSERT INTO "SubAgent" VALUES (300,'Careem');
COMMIT;
